import type { Data, Booking, User } from '../types';
import { seed, seatsFor } from '../data/seed';
const KEY='av_data_v2';
export const storageService={
 read<T>(key:string,fallback:T):T {try {const raw=localStorage.getItem(key);return raw?JSON.parse(raw):fallback;}catch{return fallback;}},
 write<T>(key:string,value:T){try{localStorage.setItem(key,JSON.stringify(value));}catch{try{localStorage.removeItem(KEY);localStorage.setItem(key,JSON.stringify(value));}catch{throw new Error('Browser storage is unavailable. Enable site storage and try again.');}}},
 remove(key:string){localStorage.removeItem(key);}
};
export interface Repository<T extends {id:string}> {list():Promise<T[]>;get(id:string):Promise<T|null>;save(value:T):Promise<void>;delete(id:string):Promise<void>}
export const emptyData=():Data=>({movies:[],theatres:[],screens:[],shows:[],bookings:[],reviews:[],users:[],settings:{requireAdminConfirmation:false}});
function normaliseData(value:unknown):Data {const saved=value&&typeof value==='object'?value as Partial<Data>:{};return {movies:Array.isArray(saved.movies)?saved.movies:[],theatres:Array.isArray(saved.theatres)?saved.theatres:[],screens:Array.isArray(saved.screens)?saved.screens:[],shows:Array.isArray(saved.shows)?saved.shows:[],bookings:Array.isArray(saved.bookings)?saved.bookings:[],reviews:Array.isArray(saved.reviews)?saved.reviews:[],users:Array.isArray(saved.users)?saved.users:[],settings:{requireAdminConfirmation:Boolean((saved.settings as Data['settings']|undefined)?.requireAdminConfirmation)}};}
export const database={read:():Data=>normaliseData(storageService.read<unknown>(KEY,emptyData())),write:(data:Data)=>{storageService.write(KEY,normaliseData(data));window.dispatchEvent(new Event('av-change'));},update:(fn:(data:Data)=>void)=>{const data=database.read();fn(data);database.write(data);}};
async function apiGet<T>(path:string):Promise<T>{const response=await fetch(`/api/v1${path}`);if(!response.ok)throw new Error(`Backend request failed (${response.status})`);return response.json();}
export async function loadBackendData(){const [movies,theatres,shows,reviews]=await Promise.all([apiGet<{content:Data['movies']}>(`/movies?size=200`),apiGet<{content:Data['theatres']}>(`/theatres?size=200`),apiGet<Data['shows']>('/shows'),apiGet<Data['reviews']>('/reviews').catch(()=>[] as Data['reviews'])]);const screens=(await Promise.all(theatres.content.map(t=>apiGet<Data['screens']>(`/theatres/${t.id}/screens`).catch(()=>[] as Data['screens'])))).flat();const data={...database.read(),movies:movies.content,theatres:theatres.content,screens,shows,reviews,bookings:[],users:[]};database.write(data);return data;}
export function repository<K extends Exclude<keyof Data,'settings'>>(key:K):Repository<Data[K][number]>{return {async list(){return database.read()[key] as Data[K][number][];},async get(id){return (database.read()[key] as Data[K][number][]).find(x=>x.id===id)||null;},async save(value){database.update(data=>{const list=data[key] as Data[K][number][];const i=list.findIndex(x=>x.id===value.id);if(i<0)list.push(value);else list[i]=value;});},async delete(id){database.update(data=>{(data[key] as {id:string}[])=(data[key] as {id:string}[]).filter(x=>x.id!==id);});}};}
export const repositories={movies:repository('movies'),theatres:repository('theatres'),screens:repository('screens'),shows:repository('shows'),bookings:repository('bookings'),reviews:repository('reviews'),users:repository('users')};
export interface PaymentService {pay(amount:number):Promise<{success:boolean;reference:string}>}
export const mockPaymentService:PaymentService={async pay(){await new Promise(r=>setTimeout(r,600));return {success:true,reference:`DEMO-${Date.now()}`};}};
export interface NotificationService {prepare(booking:Booking):Promise<string>}
export const mockNotificationService:NotificationService={async prepare(){return 'Demo: ticket email and mobile confirmation prepared. Nothing was sent.';}};
export {authService} from './auth';
export function validateBooking(data:Data,user:User,showId:string,seatIds:string[],now=new Date()){
 const show=data.shows.find(s=>s.id===showId);if(!show||show.status!=='OPEN'||new Date(`${show.date}T${show.startTime}`)<=now||(show.bookingOpens&&new Date(show.bookingOpens)>now)||(show.bookingCloses&&new Date(show.bookingCloses)<now))throw new Error('This show is unavailable for booking. Please choose another show.');
 const screen=data.screens.find(s=>s.id===show.screenId&&s.theatreId===show.theatreId&&s.status==='ACTIVE');if(!screen||!data.theatres.some(t=>t.id===show.theatreId&&t.status==='ACTIVE'))throw new Error('This theatre or screen is unavailable.');
 if(!seatIds.length||new Set(seatIds).size!==seatIds.length)throw new Error('Please select at least one available seat.');
 const active=data.bookings.filter(b=>b.showId===showId&&b.status!=='CANCELLED');
 const used=active.filter(b=>b.snapshot.mobile===user.mobile).reduce((n,b)=>n+b.ticketCount,0);
 if(used+seatIds.length>show.maxTicketsPerMobile)throw new Error(`You can book a maximum of ${show.maxTicketsPerMobile} tickets for this screening using the same mobile number. You already have ${used}.`);
 if(seatIds.some(id=>!screen.seats.some(s=>s.id===id&&!s.disabled)||active.some(b=>b.seatIds.includes(id))))throw new Error('A selected seat is already booked or unavailable. Please choose another seat.');
 return show;
}
export async function createBooking(user:User,showId:string,seatIds:string[]){
 let show=validateBooking(database.read(),user,showId,seatIds);const amount=show.ticketType==='FREE'?0:show.ticketPrice*seatIds.length;
 if(amount){const result=await mockPaymentService.pay(amount);if(!result.success)throw new Error('Demo payment failed. Please try again.');}
 let booking!:Booking;
 database.update(data=>{show=validateBooking(data,user,showId,seatIds);if(amount!==(show.ticketType==='FREE'?0:show.ticketPrice*seatIds.length))throw new Error('The price changed. Please review your booking again.');const pending=show.requireAdminConfirmation||data.settings.requireAdminConfirmation;booking={id:`AV-${crypto.randomUUID().slice(0,8).toUpperCase()}`,userId:user.id,showId,seatIds,ticketCount:seatIds.length,totalAmount:amount,status:pending?'PENDING':'CONFIRMED',confirmationStatus:pending?'PENDING':'AUTO',createdAt:new Date().toISOString(),attended:false,notification:'Demo notifications prepared; no messages sent.',snapshot:{movie:data.movies.find(m=>m.id===show.movieId)?.title||'Movie',theatre:data.theatres.find(t=>t.id===show.theatreId)!.name,screen:data.screens.find(s=>s.id===show.screenId)!.name,date:show.date,time:show.startTime,mobile:user.mobile,email:user.email}};data.bookings.push(booking);});
 const notification=await mockNotificationService.prepare(booking);await repositories.bookings.save({...booking,notification});return booking;
}
export function removeEntity(key:'movies'|'theatres'|'screens'|'shows',id:string){database.update(d=>{const showIds=(predicate:(show:typeof d.shows[number])=>boolean)=>d.shows.filter(predicate).map(show=>show.id);const removeShows=(ids:string[])=>{d.bookings=d.bookings.filter(booking=>!ids.includes(booking.showId));d.shows=d.shows.filter(show=>!ids.includes(show.id));};if(key==='movies'){const ids=showIds(show=>show.movieId===id);removeShows(ids);d.reviews=d.reviews.filter(review=>review.movieId!==id);d.movies=d.movies.filter(movie=>movie.id!==id);return;}if(key==='theatres'){const ids=showIds(show=>show.theatreId===id);removeShows(ids);d.screens=d.screens.filter(screen=>screen.theatreId!==id);d.theatres=d.theatres.filter(theatre=>theatre.id!==id);return;}if(key==='screens'){const ids=showIds(show=>show.screenId===id);removeShows(ids);d.screens=d.screens.filter(screen=>screen.id!==id);return;}if(key==='shows'){removeShows([id]);}});}
export function embedUrl(raw:string):string|null {try{const u=new URL(raw);if(!['https:','http:'].includes(u.protocol))return null;const host=u.hostname.replace(/^www\./,'');if(host==='youtube.com'||host==='m.youtube.com'||host==='youtu.be'){const id=host==='youtu.be'?u.pathname.slice(1):u.searchParams.get('v')||u.pathname.split('/').pop();return id&&/^[\w-]{11}$/.test(id)?`https://www.youtube-nocookie.com/embed/${id}`:null;}if(host==='instagram.com'&&/^\/(p|reel)\/[\w-]+/.test(u.pathname))return `https://www.instagram.com${u.pathname.replace(/\/$/,'')}/embed`;if(host==='facebook.com')return `https://www.facebook.com/plugins/video.php?href=${encodeURIComponent(raw)}`;if(host==='drive.google.com'){const id=u.pathname.match(/\/file\/d\/([^/]+)/)?.[1]||u.searchParams.get('id');return id?`https://drive.google.com/file/d/${id}/preview`:null;}return null;}catch{return null;}}
export function socialUrl(raw:string){try{const u=new URL(raw);return u.protocol==='https:'&&['youtube.com','www.youtube.com','youtu.be','instagram.com','www.instagram.com','facebook.com','www.facebook.com','drive.google.com','x.com','twitter.com'].includes(u.hostname);}catch{return false;}}

export function ensureSampleCatalogue(){
 database.update(data=>{
  const addMovie=(movie:Data['movies'][number])=>{if(!data.movies.some(item=>item.id===movie.id||item.title.toLowerCase()===movie.title.toLowerCase()))data.movies.push(movie);};
  addMovie({id:'sample-sita-ramam',title:'Sita Ramam',posterUrl:'https://image.tmdb.org/t/p/w500/8hl5Ws8C8x9B3fXxV1FSh6APwzL.jpg',trailerUrl:'https://www.youtube.com/watch?v=Ljk6tGZ1l3A',description:'A letter from the past connects two strangers in a sweeping romance shaped by memory, duty, and courage.',genre:['Romance','Drama'],language:'Telugu',duration:163,releaseDate:'2022-08-05',certification:'U',director:'Hanu Raghavapudi',cast:['Dulquer Salmaan','Mrunal Thakur','Rashmika Mandanna'],production:'Vyjayanthi Movies',status:'ACTIVE'});
  addMovie({id:'sample-lucky-bhaskar',title:'Lucky Baskhar',posterUrl:'https://image.tmdb.org/t/p/w500/49U5j8kF9iOiNW2ENZYlV7oIT5Y.jpg',trailerUrl:'https://www.youtube.com/watch?v=0b6juT8e3Do',description:'An ordinary bank cashier is pulled into an extraordinary financial gamble that changes his family forever.',genre:['Crime','Drama','Thriller'],language:'Telugu',duration:148,releaseDate:'2024-10-31',certification:'UA',director:'Venky Atluri',cast:['Dulquer Salmaan','Meenakshi Chaudhary'],production:'Sithara Entertainments',status:'ACTIVE'});
  addMovie({id:'sample-kingdom',title:'Kingdom',posterUrl:'https://image.tmdb.org/t/p/w500/9JbAqCXPqFM6lRdkOngyH4QJbTJ.jpg',trailerUrl:'https://www.youtube.com/watch?v=dQw4w9WgXcQ',description:'A young man is drawn into a dangerous mission that tests loyalty, identity, and the cost of power.',genre:['Action','Drama'],language:'Telugu',duration:155,releaseDate:'2026-10-01',certification:'UA',director:'Gowtam Tinnanuri',cast:['Vijay Deverakonda','Bhagyashri Borse'],production:'Sithara Entertainments',status:'UPCOMING'});
  const ak=data.movies.find(item=>item.title.trim().toLowerCase()==='ak');const theatre=data.theatres[0];if(!ak||!theatre)return;
  const makeScreen=(id:string,name:string,number:number,rows:number,cols:number)=>{let screen=data.screens.find(item=>item.id===id);if(!screen){screen={id,theatreId:theatre.id,name,number,rows,seatsPerRow:cols,seats:seatsFor(rows,cols),status:'ACTIVE'};data.screens.push(screen);}return screen;};
  const screenA=makeScreen('sample-ak-screen-1','Ak Premiere Hall',21,7,11);const screenB=makeScreen('sample-ak-screen-2','Ak Luxe Screen',22,6,9);const day=(offset:number)=>{const value=new Date();value.setDate(value.getDate()+offset);return value.toISOString().slice(0,10);};
  const showData=[[screenA,day(1),'11:00','13:10',180],[screenA,day(1),'18:30','20:40',220],[screenB,day(2),'15:15','17:25',250],[screenB,day(2),'21:00','23:10',250]] as const;
  showData.forEach(([screen,date,startTime,endTime,price],index)=>{const id=`sample-ak-show-${index}`;if(!data.shows.some(item=>item.id===id))data.shows.push({id,movieId:ak.id,theatreId:theatre.id,screenId:screen.id,date,startTime,endTime,ticketType:'PAID',ticketPrice:price,maxTicketsPerMobile:4,requireAdminConfirmation:false,bookingOpens:'',bookingCloses:'',status:'OPEN'});});
 });
}
