package com.example.moviebooking.booking;
import com.example.moviebooking.auth.entity.User;
import com.example.moviebooking.auth.repository.UserRepository;
import com.example.moviebooking.catalog.MovieRepository;
import com.example.moviebooking.common.exception.ApiException;
import com.example.moviebooking.notification.NotificationService;
import com.example.moviebooking.payment.*;
import com.example.moviebooking.showtime.*;
import com.example.moviebooking.venue.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.security.Principal;
import java.time.Instant;
import java.util.*;
@Service public class BookingService {
 private final BookingRepository bookings; private final ShowRepository shows; private final SeatRepository seats; private final MovieRepository movies; private final TheatreRepository theatres; private final ScreenRepository screens; private final UserRepository users; private final PaymentRepository payments; private final NotificationService notifications;
 public BookingService(BookingRepository bookings,ShowRepository shows,SeatRepository seats,MovieRepository movies,TheatreRepository theatres,ScreenRepository screens,UserRepository users,PaymentRepository payments,NotificationService notifications){this.bookings=bookings;this.shows=shows;this.seats=seats;this.movies=movies;this.theatres=theatres;this.screens=screens;this.users=users;this.payments=payments;this.notifications=notifications;}
 public List<Booking> mine(Principal p){return bookings.findByUserIdOrderByCreatedAtDesc(p.getName());}
 public Booking get(String id,Principal p){var b=bookings.findById(id).orElseThrow(()->new ApiException(404,"BOOKING_NOT_FOUND","Booking not found"));if(!b.userId.equals(p.getName()))throw new ApiException(403,"FORBIDDEN","Access denied");return b;}
 @Transactional public Booking create(Principal p,CreateBookingRequest r){User u=users.findById(p.getName()).orElseThrow(()->new ApiException(401,"UNAUTHORIZED","Authentication required"));var show=shows.findById(r.showId).orElseThrow(()->new ApiException(404,"SHOW_NOT_FOUND","Show not found"));if(show.status!=ShowStatus.OPEN)throw new ApiException(400,"SHOW_CLOSED","Show is not open for booking");var now=Instant.now();if(show.bookingOpens!=null&&now.isBefore(show.bookingOpens))throw new ApiException(400,"BOOKING_NOT_OPEN","Booking has not opened");if(show.bookingCloses!=null&&now.isAfter(show.bookingCloses))throw new ApiException(400,"BOOKING_CLOSED","Booking is closed");var requested=new ArrayList<>(new LinkedHashSet<>(r.seatIds));if(requested.size()!=r.seatIds.size())throw new ApiException(400,"DUPLICATE_SEAT","Seat selected more than once");var existing=bookings.activeByMobile(show.id,u.mobile,List.of(BookingStatus.PENDING,BookingStatus.CONFIRMED)).stream().mapToInt(b->b.ticketCount).sum();if(existing+requested.size()>show.maxTicketsPerMobile)throw new ApiException(400,"TICKET_LIMIT","Ticket limit exceeded for this mobile number");var locked=seats.lockAllByIds(requested);if(locked.size()!=requested.size())throw new ApiException(400,"INVALID_SEAT","One or more seats are invalid");if(locked.stream().anyMatch(s->!s.screen.id.equals(show.screenId)||s.disabled))throw new ApiException(400,"INVALID_SEAT","One or more seats are unavailable");if(bookings.anySeatBooked(show.id,requested,List.of(BookingStatus.PENDING,BookingStatus.CONFIRMED)))throw new ApiException(409,"SEAT_ALREADY_BOOKED","One or more seats are already booked");var movie=movies.findById(show.movieId).orElseThrow();var theatre=theatres.findById(show.theatreId).orElseThrow();var screen=screens.findById(show.screenId).orElseThrow();var b=new Booking();b.userId=u.id;b.showId=show.id;b.seatIds=requested;b.ticketCount=requested.size();b.totalAmount=show.ticketPrice.multiply(java.math.BigDecimal.valueOf(requested.size()));b.status=show.ticketType==TicketType.FREE&&!show.requireAdminConfirmation?BookingStatus.CONFIRMED:BookingStatus.PENDING;b.confirmationStatus=show.requireAdminConfirmation?ConfirmationStatus.PENDING:ConfirmationStatus.AUTO;b.movie=movie.title;b.theatre=theatre.name;b.screen=screen.name;b.date=show.date.toString();b.time=show.startTime.toString();b.mobile=u.mobile;b.email=u.email;b.notification=notifications.record(u.id,"BOOKING_CREATED","Booking "+b.status.name().toLowerCase()+" for "+movie.title);bookings.save(b);var pay=new Payment();pay.bookingId=b.id;pay.amount=b.totalAmount;pay.status=show.ticketType==TicketType.FREE?PaymentStatus.NOT_REQUIRED:PaymentStatus.PENDING;payments.save(pay);return b;}
 @Transactional public Booking cancel(String id,Principal p){var b=get(id,p);if(b.status==BookingStatus.CANCELLED)return b;b.status=BookingStatus.CANCELLED;b.notification=notifications.record(b.userId,"BOOKING_CANCELLED","Booking cancelled for "+b.movie);return b;}
 @Transactional public Booking adminConfirm(String id){var b=bookings.findById(id).orElseThrow(()->new ApiException(404,"BOOKING_NOT_FOUND","Booking not found"));b.status=BookingStatus.CONFIRMED;b.confirmationStatus=ConfirmationStatus.CONFIRMED;b.notification=notifications.record(b.userId,"BOOKING_CONFIRMED","Booking confirmed for "+b.movie);return b;}
 @Transactional public Booking markAttended(String id,boolean attended){var b=bookings.findById(id).orElseThrow(()->new ApiException(404,"BOOKING_NOT_FOUND","Booking not found"));b.attended=attended;return b;}
}
