CREATE TABLE users (
 id VARCHAR(36) PRIMARY KEY, name VARCHAR(150) NOT NULL,
 mobile VARCHAR(20) NOT NULL UNIQUE, email VARCHAR(255) UNIQUE,
 role VARCHAR(20) NOT NULL DEFAULT 'USER', enabled BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMP(6) NOT NULL, updated_at TIMESTAMP(6) NOT NULL
);
