CREATE TABLE otp_verifications (
 id BIGINT AUTO_INCREMENT PRIMARY KEY, mobile VARCHAR(20) NOT NULL,
 otp_hash VARCHAR(255) NOT NULL, expires_at TIMESTAMP(6) NOT NULL,
 attempt_count INT NOT NULL DEFAULT 0, verified BOOLEAN NOT NULL DEFAULT FALSE,
 created_at TIMESTAMP(6) NOT NULL
);
CREATE INDEX idx_otp_mobile_created ON otp_verifications(mobile,created_at);
CREATE INDEX idx_otp_expiry ON otp_verifications(expires_at);
CREATE TABLE auth_locks (id INT PRIMARY KEY);
INSERT INTO auth_locks(id) VALUES (0);
INSERT INTO auth_locks(id) VALUES (1);
INSERT INTO auth_locks(id) VALUES (2);
INSERT INTO auth_locks(id) VALUES (3);
INSERT INTO auth_locks(id) VALUES (4);
INSERT INTO auth_locks(id) VALUES (5);
INSERT INTO auth_locks(id) VALUES (6);
INSERT INTO auth_locks(id) VALUES (7);
INSERT INTO auth_locks(id) VALUES (8);
INSERT INTO auth_locks(id) VALUES (9);
INSERT INTO auth_locks(id) VALUES (10);
INSERT INTO auth_locks(id) VALUES (11);
INSERT INTO auth_locks(id) VALUES (12);
INSERT INTO auth_locks(id) VALUES (13);
INSERT INTO auth_locks(id) VALUES (14);
INSERT INTO auth_locks(id) VALUES (15);
INSERT INTO auth_locks(id) VALUES (16);
INSERT INTO auth_locks(id) VALUES (17);
INSERT INTO auth_locks(id) VALUES (18);
INSERT INTO auth_locks(id) VALUES (19);
INSERT INTO auth_locks(id) VALUES (20);
INSERT INTO auth_locks(id) VALUES (21);
INSERT INTO auth_locks(id) VALUES (22);
INSERT INTO auth_locks(id) VALUES (23);
INSERT INTO auth_locks(id) VALUES (24);
INSERT INTO auth_locks(id) VALUES (25);
INSERT INTO auth_locks(id) VALUES (26);
INSERT INTO auth_locks(id) VALUES (27);
INSERT INTO auth_locks(id) VALUES (28);
INSERT INTO auth_locks(id) VALUES (29);
INSERT INTO auth_locks(id) VALUES (30);
INSERT INTO auth_locks(id) VALUES (31);
INSERT INTO auth_locks(id) VALUES (32);
INSERT INTO auth_locks(id) VALUES (33);
INSERT INTO auth_locks(id) VALUES (34);
INSERT INTO auth_locks(id) VALUES (35);
INSERT INTO auth_locks(id) VALUES (36);
INSERT INTO auth_locks(id) VALUES (37);
INSERT INTO auth_locks(id) VALUES (38);
INSERT INTO auth_locks(id) VALUES (39);
INSERT INTO auth_locks(id) VALUES (40);
INSERT INTO auth_locks(id) VALUES (41);
INSERT INTO auth_locks(id) VALUES (42);
INSERT INTO auth_locks(id) VALUES (43);
INSERT INTO auth_locks(id) VALUES (44);
INSERT INTO auth_locks(id) VALUES (45);
INSERT INTO auth_locks(id) VALUES (46);
INSERT INTO auth_locks(id) VALUES (47);
INSERT INTO auth_locks(id) VALUES (48);
INSERT INTO auth_locks(id) VALUES (49);
INSERT INTO auth_locks(id) VALUES (50);
INSERT INTO auth_locks(id) VALUES (51);
INSERT INTO auth_locks(id) VALUES (52);
INSERT INTO auth_locks(id) VALUES (53);
INSERT INTO auth_locks(id) VALUES (54);
INSERT INTO auth_locks(id) VALUES (55);
INSERT INTO auth_locks(id) VALUES (56);
INSERT INTO auth_locks(id) VALUES (57);
INSERT INTO auth_locks(id) VALUES (58);
INSERT INTO auth_locks(id) VALUES (59);
INSERT INTO auth_locks(id) VALUES (60);
INSERT INTO auth_locks(id) VALUES (61);
INSERT INTO auth_locks(id) VALUES (62);
INSERT INTO auth_locks(id) VALUES (63);
