INSERT IGNORE INTO movies (id,title,poster_url,backdrop_url,trailer_url,description,language,duration,release_date,certification,director,production,status,created_at,updated_at) VALUES
('m01','Interstellar','https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg','https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK5VQsXEG.jpg','https://www.youtube.com/watch?v=zSWdZVtXT7E','A team of explorers travels beyond the galaxy to secure humanity’s future.','English',169,'2014-11-07','UA','Christopher Nolan','Paramount Pictures','ACTIVE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('m02','Dune: Part Two','https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',NULL,'https://www.youtube.com/watch?v=Way9Dexny3w','Paul Atreides unites with the Fremen in an epic battle for Arrakis.','English',166,'2024-03-01','UA','Denis Villeneuve','Legendary Pictures','ACTIVE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('m03','RRR','https://image.tmdb.org/t/p/w500/nEufeZlyAOLqO2brrs0yeF1lgXO.jpg',NULL,'https://www.youtube.com/watch?v=NgBoMJy386M','Two revolutionaries form an unforgettable friendship while fighting for freedom.','Telugu',187,'2022-03-25','UA','S. S. Rajamouli','DVV Entertainment','ACTIVE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('m04','Kalki 2898 AD','https://image.tmdb.org/t/p/w500/rstcAnBeCkxNQjNp3YXrF6IP1tW.jpg',NULL,'https://www.youtube.com/watch?v=y1-w1kUGuz8','A mysterious protector rises in a dystopian future.','Telugu',181,'2024-06-27','UA','Nag Ashwin','Vyjayanthi Movies','ACTIVE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('m05','Sita Ramam','https://image.tmdb.org/t/p/w500/8hl5Ws8C8x9B3fXxV1FSh6APwzL.jpg',NULL,'https://www.youtube.com/watch?v=Ljk6tGZ1l3A','A letter from the past connects two strangers across time.','Telugu',163,'2022-08-05','U','Hanu Raghavapudi','Vyjayanthi Movies','ACTIVE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('m06','Lucky Baskhar','https://image.tmdb.org/t/p/w500/49U5j8kF9iOiNW2ENZYlV7oIT5Y.jpg',NULL,'https://www.youtube.com/watch?v=0b6juT8e3Do','An ordinary cashier enters an extraordinary financial gamble.','Telugu',148,'2024-10-31','UA','Venky Atluri','Sithara Entertainments','ACTIVE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('m07','Oppenheimer','https://image.tmdb.org/t/p/w500/ptpr0kGAckfQkJeJIt8st5dglvd.jpg',NULL,'https://www.youtube.com/watch?v=uYPbbksJxIg','The story of the scientist behind the atomic bomb.','English',180,'2023-07-21','UA','Christopher Nolan','Universal Pictures','ACTIVE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('m08','The Last Voyage','https://images.unsplash.com/photo-1500534623283-312aade485b7?w=800','https://images.unsplash.com/photo-1500534623283-312aade485b7?w=1200','https://drive.google.com/file/d/1examplevoyage/view','A crew discovers an abandoned signal at the edge of the ocean.','English',132,'2026-02-14','UA','Mira Sen','AV Originals','UPCOMING',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('m09','Monsoon Letters','https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800',NULL,'https://www.youtube.com/watch?v=dQw4w9WgXcQ','A family story unfolds through letters written during the monsoon.','Hindi',124,'2026-07-10','U','Rohan Mehta','Rainlight Studios','UPCOMING',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('m10','City of Echoes','https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=800',NULL,'https://www.youtube.com/watch?v=dQw4w9WgXcQ','A musician follows hidden recordings through a changing city.','Tamil',139,'2026-09-18','UA','Anika Rao','South Street Films','UPCOMING',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

INSERT IGNORE INTO theatres (id,name,address,city,state,contact,status,map_url,created_at,updated_at) VALUES
('t01','AV Cinemas Hyderabad','Road No. 36, Jubilee Hills','Hyderabad','Telangana','040 4000 1234','ACTIVE','https://maps.google.com/?q=Jubilee+Hills',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('t02','Prasads Multiplex','NTR Marg, Khairatabad','Hyderabad','Telangana','040 4000 5678','ACTIVE','https://maps.google.com/?q=Prasads+Multiplex',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('t03','PVR Phoenix','Lower Parel','Mumbai','Maharashtra','022 4000 1001','ACTIVE','https://maps.google.com/?q=Phoenix+Palladium',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('t04','INOX Forum Mall','Koramangala','Bengaluru','Karnataka','080 4000 1002','ACTIVE','https://maps.google.com/?q=Forum+Mall+Bengaluru',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('t05','PVR Director’s Cut','Vasant Kunj','New Delhi','Delhi','011 4000 1003','ACTIVE','https://maps.google.com/?q=Vasant+Kunj',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('t06','Cinepolis One','Salt Lake Sector V','Kolkata','West Bengal','033 4000 1004','ACTIVE','https://maps.google.com/?q=Salt+Lake+Kolkata',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('t07','Miraj Cinemas','Banjara Hills','Pune','Maharashtra','020 4000 1005','ACTIVE','https://maps.google.com/?q=Banjara+Hills+Pune',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('t08','Luxe Cinemas','Anna Salai','Chennai','Tamil Nadu','044 4000 1006','ACTIVE','https://maps.google.com/?q=Anna+Salai+Chennai',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('t09','Rajhans Cinema','Navrangpura','Ahmedabad','Gujarat','079 4000 1007','ACTIVE','https://maps.google.com/?q=Navrangpura',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('t10','Carnival Cinemas','Panampilly Nagar','Kochi','Kerala','0484 4000 1008','ACTIVE','https://maps.google.com/?q=Panampilly+Nagar',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

INSERT IGNORE INTO screens (id,theatre_id,name,number,row_count,seats_per_row,status,created_at,updated_at) SELECT CONCAT('s',LPAD(n,2,'0')),CONCAT('t',LPAD(n,2,'0')), 'Main Screen',1,8,12,'ACTIVE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM (SELECT 1 n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) x;

INSERT IGNORE INTO shows (id,movie_id,theatre_id,screen_id,date,start_time,end_time,ticket_type,ticket_price,max_tickets_per_mobile,require_admin_confirmation,status,created_at,updated_at)
SELECT CONCAT('show',LPAD(n,2,'0')),CONCAT('m',LPAD(n,2,'0')),CONCAT('t',LPAD(n,2,'0')),CONCAT('s',LPAD(n,2,'0')),DATEADD('DAY', 2, CURRENT_DATE),'18:00:00','21:00:00','PAID',250,6,FALSE,'OPEN',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM (SELECT 1 n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) x;
