import {useMemo, useState} from 'react';
import {Armchair, GripVertical, Plus, Save, Trash2} from 'lucide-react';
import {useApp} from '../context/AppContext';
import {repositories} from '../services/api';
import {Empty, Notice, SectionHeading} from '../components/Common';
import type {Seat} from '../types';

const position=(seat:Seat,index:number,columns:number)=>({row:seat.row??Math.floor(index/columns)+1,column:seat.column??index%columns+1});
const rowName=(row:number)=>String.fromCharCode(64+row);

export function LayoutBuilder({initialScreenId}:{initialScreenId?:string}={}){
  const {data}=useApp();
  const [screenId,setScreenId]=useState(initialScreenId||data.screens[0]?.id||'');
  const screen=data.screens.find(item=>item.id===screenId);
  const [columns,setColumns]=useState(()=>Math.max(1,screen?.seatsPerRow||12));
  const [seats,setSeats]=useState<Seat[]>(()=>screen?.seats.map((seat,index)=>({...seat,...position(seat,index,screen.seatsPerRow)}))||[]);
  const [tool,setTool]=useState<'REGULAR'|'PREMIUM'|'disabled'|'remove'>('REGULAR');
  const [dragged,setDragged]=useState<string|null>(null); const [message,setMessage]=useState(''); const [error,setError]=useState('');
  const rows=useMemo(()=>Math.max(6,...seats.map((seat,index)=>position(seat,index,columns).row)),[seats,columns]);
  if(!screen)return <Empty title="Add a screen before configuring its layout."/>;
  const usedSeatIds=new Set(data.bookings.filter(booking=>booking.status!=='CANCELLED'&&data.shows.some(show=>show.id===booking.showId&&show.screenId===screen.id)).flatMap(booking=>booking.seatIds));
  const relabel=(input:Seat[])=>input.map((seat,index)=>{const point=position(seat,index,columns);const number=input.filter((candidate,candidateIndex)=>{const candidatePoint=position(candidate,candidateIndex,columns);return candidatePoint.row===point.row&&candidatePoint.column<=point.column;}).length;return {...seat,id:`${rowName(point.row)}${number}`,row:point.row,column:point.column};});
  const chooseScreen=(id:string)=>{const next=data.screens.find(item=>item.id===id);setScreenId(id);setColumns(Math.max(1,next?.seatsPerRow||12));setSeats(next?.seats.map((seat,index)=>({...seat,...position(seat,index,next.seatsPerRow)}))||[]);setMessage('');setError('');};
  const at=(row:number,column:number)=>seats.find((seat,index)=>{const point=position(seat,index,columns);return point.row===row&&point.column===column;});
  const addSeat=(row:number)=>{const occupied=seats.filter((seat,index)=>position(seat,index,columns).row===row).map((seat,index)=>position(seat,index,columns).column);const column=Array.from({length:columns},(_,index)=>index+1).find(value=>!occupied.includes(value));if(!column){setError('This row is full. Add a column, or move or remove a seat first.');return;}setSeats(current=>relabel([...current,{id:`${rowName(row)}1`,category:'REGULAR',disabled:false,row,column}]));};
  const apply=(row:number,column:number)=>{const seat=at(row,column);if(!seat){addSeat(row);return;}if(tool==='remove'){if(usedSeatIds.has(seat.id)){setError(`${seat.id} has booking history and cannot be removed.`);return;}setSeats(current=>relabel(current.filter(item=>item.id!==seat.id)));return;}setSeats(current=>current.map(item=>item.id!==seat.id?item:tool==='disabled'?{...item,disabled:!item.disabled}:{...item,category:tool,disabled:false}));};
  const drop=(row:number,column:number)=>{if(!dragged)return;const moving=seats.find(seat=>seat.id===dragged);if(!moving)return;const target=at(row,column);const movingPoint=position(moving,seats.indexOf(moving),columns);setSeats(current=>relabel(current.map(seat=>seat.id===moving.id?{...seat,row,column}:target&&seat.id===target.id?{...seat,row:movingPoint.row,column:movingPoint.column}:seat)));setDragged(null);};
  const save=async()=>{try{await repositories.screens.save({...screen,seats,seatsPerRow:columns,rows});setMessage('Layout saved. Seats are renumbered left to right after removals.');setError('');}catch(reason){setError((reason as Error).message);}};
  return <div className="admin-content layout-builder"><SectionHeading eyebrow="CUSTOM SEAT MAP" title="Build the theatre exactly as it is." description="Drag seats into place. Empty cells become aisles, gaps, wheelchair spaces, or row breaks."/><div className="layout-toolbar panel"><label>Screen<select value={screenId} onChange={event=>chooseScreen(event.target.value)}>{data.screens.map(item=><option value={item.id} key={item.id}>{data.theatres.find(theatre=>theatre.id===item.theatreId)?.name} · {item.name}</option>)}</select></label><div className="layout-tools">{(['REGULAR','PREMIUM','disabled','remove'] as const).map(item=><button type="button" className={tool===item?'active':''} key={item} onClick={()=>setTool(item)}>{item==='remove'?<Trash2 size={15}/>:<Armchair size={15}/>} {item==='disabled'?'Unavailable':item==='remove'?'Remove seat':item}</button>)}</div><button className="button" onClick={save}><Save size={16}/> Save layout</button></div>{message&&<Notice>{message}</Notice>}{error&&<Notice error>{error}</Notice>}<div className="layout-instructions"><span><GripVertical size={15}/> Drag a seat to move it.</span><span><Plus size={15}/> Click an empty cell to add a seat.</span><span>Removing A3 renumbers A4 to A3.</span></div><section className="layout-canvas panel"><div className="cinema-screen">SCREEN</div><div className="custom-seat-grid" style={{gridTemplateColumns:`repeat(${columns}, 42px)`}}>{Array.from({length:rows*columns},(_,index)=>{const row=Math.floor(index/columns)+1;const column=index%columns+1;const seat=at(row,column);return <button type="button" key={`${row}-${column}`} className={`layout-cell ${seat?'occupied':''} ${seat?.category==='PREMIUM'?'premium':''} ${seat?.disabled?'booked':''}`} draggable={!!seat} onDragStart={()=>seat&&setDragged(seat.id)} onDragOver={event=>event.preventDefault()} onDrop={()=>drop(row,column)} onClick={()=>apply(row,column)}>{seat?<><span>{seat.id}</span><GripVertical size={11}/></>:<Plus size={13}/>}</button>})}</div><div className="layout-expand"><button className="add-row" onClick={()=>setSeats(current=>relabel([...current,{id:`${rowName(rows+1)}1`,category:'REGULAR',disabled:false,row:rows+1,column:1}]))}><Plus size={16}/> Add row</button><button className="add-row" onClick={()=>setColumns(current=>Math.min(30,current+1))}><Plus size={16}/> Add column</button></div></section></div>;
}
