package com.example.moviebooking.notification;
import com.example.moviebooking.auth.provider.EmailProvider;
import com.example.moviebooking.auth.entity.User;
import com.example.moviebooking.auth.repository.UserRepository;
import com.example.moviebooking.booking.*;
import com.example.moviebooking.showtime.ShowRepository;
import com.example.moviebooking.common.exception.ApiException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import java.util.*;
import java.util.stream.Collectors;
@Service public class NotificationService {
 private static final Logger log=LoggerFactory.getLogger(NotificationService.class);
 private final NotificationRepository notifications; private final UserRepository users; private final BookingRepository bookings; private final ShowRepository shows; private final EmailProvider email; private final WhatsAppProvider whatsapp;
 public NotificationService(NotificationRepository notifications,UserRepository users,BookingRepository bookings,ShowRepository shows,EmailProvider email,WhatsAppProvider whatsapp){this.notifications=notifications;this.users=users;this.bookings=bookings;this.shows=shows;this.email=email;this.whatsapp=whatsapp;}
 public String record(String userId,String type,String message){var n=new Notification();n.userId=userId;n.type=type;n.message=message;notifications.save(n);return message;}
 public void sendTicket(User user,Booking booking){String body="Hi "+safeName(user.name)+", your movie ticket is ready.\nMovie: "+booking.movie+"\nVenue: "+booking.theatre+"\nScreen: "+booking.screen+"\nShow: "+booking.date+" at "+booking.time+"\nSeats: "+String.join(", ",booking.seatIds)+"\nTickets: "+booking.ticketCount+"\nAmount: "+booking.totalAmount+"\nBooking: "+booking.id+"\nTicket code: "+booking.ticketCode;try{dispatch(user,"BOOKING_TICKET","Your ticket for "+booking.movie,body,"BOTH");}catch(RuntimeException e){log.warn("Ticket {} saved, but message delivery failed: {}",booking.id,e.getMessage());record(user.id,"BOOKING_TICKET_DELIVERY_PENDING","Ticket details for "+booking.movie+" are saved in My Bookings. External message delivery can be retried.");}}
 @Transactional public CampaignResult send(CampaignRequest request){
  String channel=request.channel().trim().toUpperCase(Locale.ROOT);if(!Set.of("EMAIL","WHATSAPP","BOTH").contains(channel))throw new ApiException(400,"INVALID_CHANNEL","Choose email, WhatsApp, or both.");
  if(channel.equals("WHATSAPP")&&!whatsapp.isConfigured())throw new ApiException(503,"WHATSAPP_NOT_CONFIGURED","Configure the WhatsApp HTTPS webhook before sending WhatsApp-only messages.");
  if(request.target()!=CampaignRequest.Target.ALL_USERS&&request.target()!=CampaignRequest.Target.SHOW_BOOKERS&&(request.movieId()==null||request.movieId().isBlank()))throw new ApiException(400,"MOVIE_REQUIRED","Choose a movie audience.");
  if(request.target()==CampaignRequest.Target.SHOW_BOOKERS&&(request.showId()==null||!shows.existsById(request.showId())))throw new ApiException(404,"SHOW_NOT_FOUND","Choose an existing show.");
  var showIds=request.target()==CampaignRequest.Target.SHOW_BOOKERS?List.of(request.showId()):request.target()==CampaignRequest.Target.MOVIE_BOOKERS?shows.findAll().stream().filter(s->s.movieId.equals(request.movieId())).map(s->s.id).toList():List.<String>of();
  var booked=request.target()==CampaignRequest.Target.ALL_USERS?List.<Booking>of():request.target()==CampaignRequest.Target.SHOW_BOOKERS?bookings.findByShowId(request.showId()):showIds.isEmpty()?List.<Booking>of():bookings.findByShowIdIn(showIds);
  Set<String> ids=booked.stream().filter(b->b.status!=BookingStatus.CANCELLED).map(b->b.userId).collect(Collectors.toSet());
  var recipients=users.findByEnabledTrue().stream().filter(u->request.target()==CampaignRequest.Target.ALL_USERS||ids.contains(u.id)).filter(u->request.status()==null||request.status().isBlank()||booked.stream().anyMatch(b->b.userId.equals(u.id)&&b.status.name().equalsIgnoreCase(request.status()))).toList();
  Comparator<User> comparator=switch(request.sortBy()==null?"name":request.sortBy().toLowerCase(Locale.ROOT)){case "email"->Comparator.comparing(u->Objects.toString(u.email,""),String.CASE_INSENSITIVE_ORDER);case "joined"->Comparator.comparing(u->u.createdAt);case "mobile"->Comparator.comparing(u->u.mobile);default->Comparator.comparing(u->u.name,String.CASE_INSENSITIVE_ORDER);};var sorted=new ArrayList<>(recipients);sorted.sort(comparator);if("desc".equalsIgnoreCase(request.sortDirection()))Collections.reverse(sorted);
  int sent=0,skipped=0;for(User user:sorted){if(channel.equals("EMAIL")&&blank(user.email)||channel.equals("WHATSAPP")&&blank(user.mobile)||channel.equals("BOTH")&&blank(user.email)&&(!whatsapp.isConfigured()||blank(user.mobile))){skipped++;continue;}String body=personalize(request.message(),user,booked);dispatch(user,"ADMIN_CAMPAIGN",request.subject(),body,channel);sent++;}String deliveredChannel=channel.equals("BOTH")&&!whatsapp.isConfigured()?"EMAIL (WhatsApp not configured)":channel;return new CampaignResult(sorted.size(),sent,skipped,deliveredChannel);
 }
 @Transactional public CampaignResult sendShowReminder(String showId,String channel){var show=shows.findById(showId).orElseThrow(()->new ApiException(404,"SHOW_NOT_FOUND","Show not found"));var movieShows=List.of(showId);var rows=bookings.findByShowIdIn(movieShows).stream().filter(b->b.status!=BookingStatus.CANCELLED).toList();var ids=rows.stream().map(b->b.userId).collect(Collectors.toSet());var request=new CampaignRequest(CampaignRequest.Target.SHOW_BOOKERS,channel,"Reminder: "+rows.stream().findFirst().map(b->b.movie).orElse("your movie") ,"Hi {{name}}, a reminder for {{movie}} on {{show_date}} at {{show_time}}. Booking {{booking_id}}.",showId,null,null,"name","asc");return send(request);}
 private void dispatch(User user,String type,String subject,String body,String channel){String delivered="";if((channel.equals("EMAIL")||channel.equals("BOTH"))&&!blank(user.email)){email.send(user.email,subject,body);delivered=" email";}if((channel.equals("WHATSAPP")||channel.equals("BOTH"))&&!blank(user.mobile)&&whatsapp.isConfigured()){whatsapp.send(user.mobile,body);delivered+=" WhatsApp";}else if(channel.equals("BOTH")&&!whatsapp.isConfigured())delivered+=" WhatsApp not configured";record(user.id,type,truncate(subject+": "+body+" [delivery:"+delivered.trim()+"]"));}
 private String personalize(String template,User user,List<Booking> rows){Booking booking=rows.stream().filter(b->b.userId.equals(user.id)).findFirst().orElse(null);return template.replace("{{name}}",safeName(user.name)).replace("{{email}}",Objects.toString(user.email,"")).replace("{{mobile}}",Objects.toString(user.mobile,"")).replace("{{movie}}",booking==null?"":booking.movie).replace("{{show_date}}",booking==null?"":booking.date).replace("{{show_time}}",booking==null?"":booking.time).replace("{{booking_id}}",booking==null?"":booking.id);}
 private String safeName(String name){return name==null||name.isBlank()?"there":name.trim();}private boolean blank(String value){return value==null||value.isBlank();}private String truncate(String value){return value.length()>490?value.substring(0,487)+"...":value;}
}
