export interface Movie {id:string;title:string;posterUrl:string;backdropUrl?:string;trailerUrl:string;description:string;genre:string[];language:string;duration:number;releaseDate:string;certification:string;director:string;cast:string[];production:string;status:'UPCOMING'|'ACTIVE'|'ENDED'}
export interface VenueMedia {id:string;type:'IMAGE'|'VIDEO';url:string;title:string}
export interface Theatre {id:string;name:string;address:string;city:string;state:string;contact:string;status:'ACTIVE'|'INACTIVE';mapUrl?:string;media?:VenueMedia[]}
export interface Seat {id:string;category:'REGULAR'|'PREMIUM';disabled:boolean;row?:number;column?:number}
export interface Screen {id:string;theatreId:string;name:string;number:number;rows:number;seatsPerRow:number;seats:Seat[];status:'ACTIVE'|'INACTIVE'}
export interface Show {id:string;movieId:string;theatreId:string;screenId:string;date:string;startTime:string;endTime:string;ticketType:'FREE'|'PAID';ticketPrice:number;maxTicketsPerMobile:number;requireAdminConfirmation:boolean;bookingOpens:string;bookingCloses:string;status:'OPEN'|'CLOSED'|'CANCELLED'}
export interface User {id:string;mobile:string;name:string;email:string;createdAt:string;role?:'USER'|'ADMIN';enabled?:boolean}
export interface Booking {id:string;userId:string;showId:string;seatIds:string[];ticketCount:number;totalAmount:number;status:'PENDING'|'CONFIRMED'|'CANCELLED';confirmationStatus:'AUTO'|'PENDING'|'CONFIRMED';createdAt:string;attended:boolean;notification:string; snapshot:{movie:string;theatre:string;screen:string;date:string;time:string;mobile:string;email:string}}
export interface Review {id:string;movieId:string;userId?:string;author:string;title:string;text:string;rating:number;videoUrl:string;platform:'YOUTUBE'|'INSTAGRAM'|'FACEBOOK'|'OTHER';thumbnail:string;isHighlighted:boolean;status:'PENDING'|'APPROVED'|'REJECTED';createdAt:string}
export interface Data {movies:Movie[];theatres:Theatre[];screens:Screen[];shows:Show[];bookings:Booking[];reviews:Review[];users:User[];settings:{requireAdminConfirmation:boolean}}
